query ($id: ID!) {
  recipe(id: $id) {
    data {
      id
      attributes {
        name
        duration
        servings
        img
        description
        ingredients
        steps
        likes
        category {
          data {
            id
            attributes {
              name
              slug
            }
          }
        }
        author {
          data {
            attributes {
              username
            }
          }
        }
      }
    }
  }
}
