query ($slug: String!) {
  recipes(filters: { category: { slug: { eq: $slug } } }) {
    data {
      id
      attributes {
        name
        img
        likes
        category {
          data {
            id
            attributes {
              name
              slug
            }
          }
        }
        author {
          data {
            attributes {
              username
            }
          }
        }
      }
    }
  }
}
