query ($id: ID!) {
  usersPermissionsUser(id: $id) {
    data {
      id
      attributes {
        favorites {
          data {
            id
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
