query ($id: ID!) {
  recipes(filters: { author: { id: { eq: $id } } }) {
    data {
      id
      attributes {
        name
        category {
          data {
            id
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
